### ISSUE TITLE
Could not find the required component 'pointgrey_camera_driver'

### ISSUE THREAD

**Issue by Jinghao-coding** [CoderWangcai/DRL_Path_Planning#1]
在catkin_make的时候出现Could not find the required component 'pointgrey_camera_driver'问题，通过 sudo apt-get install ros-kinetic-pointgrey-camera-driver安装
报 E: 无法定位软件包 ros-kinetic-pointgrey-camera-driver的错误，然后找不到这个package

**Comment by CoderWangcai** [comment]
你好，

	请不要用sudo apt-get install ros-kinetic-pointgrey-camera-driver安装，直接去github上搜pointgrey-camera-driver，然后git clone这个包到你的工作空间，再编译。

Best regards,
Wangcai
